version: '3.1'
services:
  db:
    image: postgres:12-alpine3.14
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mealybug
      ALLOW_IP_RANGE: 0.0.0.0/0
  seq:
    image: datalust/seq:latest
    restart: always
    ports:
      - 5341:80
    volumes:
      - ./data/seq:/data
    environment:
      ACCEPT_EULA: Y